### ISSUE TITLE
Add zenhub functionality to repo

### ISSUE THREAD

**Issue by baconbm** [smacademic/project-bdf#10]
As of now we are not utilizing zenhub to track issues. We should take advantage of this product and use it to group and track our issues.

I would propose a system similar to what is used in dassl.

Something like 'new issues -> backlog -> milestone -> in progress -> in review -> closed' should work. 

Let me know what you guys think of this.

**Comment by afig** [comment]
There is not really much of a setup to start using ZenHub for our repo, so it wouldn't take much effort to start using it apart from installing the extension and signing in.

I agree that the system used in DASSL (which is similar to the default pipelines, with the addition of the milestone pipeline) would work well for us.

As mentioned in MS Teams, we should also figure out how we plan to use story points to organize our work.

**Comment by calebeda** [comment]
I think using ZenHub is a great idea and I agree that we should use a system similar to what dassl uses

**Comment by baconbm** [comment]
Zenhub functionality added
