### ISSUE TITLE
Bot is not able to transcribe text within image in some cases

### ISSUE THREAD

**Issue by baconbm** [smacademic/project-bdf#27]
**Describe the bug**
In some cases the bot is not able to discern what the text is within an image. Either it can only see some of the text within an image or none at all.

**To Reproduce**
1. Run `textifyBot.py`
2. See that some text is transcribed in broken English or unintelligible

**Expected behavior**
The bot is expected to transcribe the text within an image accurately.

**Additional context**
There are some potential fixes out there. Post processing the image to make the text easier to see against the background is an option. Bluring the background or making the image black and white have produced good results in other projects.

**Comment by afig** [comment]
We should gather a set of sample images that are representative of what is commonly posted on Reddit and include them in the repo as test data.

Our goal is to near-perfectly transcribe screenshots of Twitter posts. Other images can be included as stretch goals.

**Comment by baconbm** [comment]
I've implemented an initial pre-processing function for images. I have one result to share of a twitter image that went through the pre-processing to see how the results of the tesseract worked on it. This is obviously a small sample size but we may be able to have some takeaways from it.

Here is the original image- 
![original-41408798](https://user-images.githubusercontent.com/34491821/55494568-04660500-5609-11e9-816b-3e4034749ad6.png)

Here is the image after being processed -
![improved-41408798](https://user-images.githubusercontent.com/34491821/55494587-13e54e00-5609-11e9-8a04-ffb3cfa4eda4.png)

Here is the text extracted without pre-processing -
![original-tesseract-text](https://user-images.githubusercontent.com/34491821/55494610-1f387980-5609-11e9-9e0c-a415a4272fe3.JPG)

And finally here is the text extracted after the pre-processing - 
![improved-tesseract-text](https://user-images.githubusercontent.com/34491821/55494654-2e1f2c00-5609-11e9-8207-8301ac592b56.JPG)

Some takeaways -

After the processing some of the extraneous characters are lost that may cause us difficulty in transcribing. Also after the processing the author of the tweet is completely lost and the date/time of the tweet is lost.

It does not appear that the actual 'meat' of the tweet is changed much at all. This does not surprise me because the text is easily readable in the initial tweet. Where this processing would come in handy is if the text is difficult to make out, the processing will probably improve the readability.

As of now I am not certain whether the processing technique I used is a net positive, we will have to discuss this. Perhaps a different processing technique would produce better results.

**Comment by baconbm** [comment]
Here is a different method of pre-processing the image. In the above  I converted the image to greyscale and then processed the pixels one by one assigning them to either black or white depending on which color each pixel was closest to. In the following snip I increased the size of the original image a little bit but did not change the colors of the pixels. -

![improved-tesseract-text-resize](https://user-images.githubusercontent.com/34491821/55497463-66296d80-560f-11e9-8198-1946a63caa98.JPG)

In my opinion this seems a little bit better even though it captured some garbage at the bottom corresponding to the 'hearts', 'retweets', etc. It did correctly identify the '!' at the end of the tweet which the other technique incorrectly identified as an 'l'.

Interestingly, combining the two techniques (increasing the size and converting to greyscale) produced a worse result than when I tried them both separately.

**Comment by afig** [comment]
The second processing method does have pretty good good results. However, I wonder what effect the pre-processing has on images that were very hard for Tesseract to process in the first place. Twitter posts are relatively easy, maybe we could try it on some handwriting or non-screenshots?

**Comment by baconbm** [comment]
I just tested it on some handwriting. It appears that the increase method works the best on transcribing as it did with the twitter post, however it still has a lot of difficulty with handwriting. Here is the original image - 
![AAA-AAA_smitrobe_43260](https://user-images.githubusercontent.com/34491821/55499079-16e53c00-5613-11e9-9b1c-2c7470385a20.jpg)

Transcribing with no processing at all -
![image](https://user-images.githubusercontent.com/34491821/55499105-2cf2fc80-5613-11e9-9774-1c7f85bb2988.png)

Transcribing after increasing size - 
![image](https://user-images.githubusercontent.com/34491821/55499126-4005cc80-5613-11e9-8070-0113bf00726f.png)
