### ISSUE TITLE
Create File Structure

### ISSUE THREAD

**Issue by baconbm** [smacademic/project-bdf#3]
Since this is a new project, we need to decide the file structure we will need to accommodate our bot. We already have a docs folder, so we will need to consider what other folders will be needed. 

We should be able to narrow down on a more concrete folder structure as we decide what technologies will be needed.

**Comment by afig** [comment]
I think a simple file/folder structure should be sufficient for our needs. Something like: 

```
/docs
/src
/tests
    /data
```

I do not think we'll need any sub-folders other than the `/data` one noted above. We should avoid having full copies of our dependencies in the repo, and instead use standardized means for declaring what dependencies our application has. [pipenv](https://packaging.python.org/tutorials/managing-dependencies/) seems to be a pretty common solution for managing dependencies in Python.

**Comment by baconbm** [comment]
I agree, we don't need anything fancier than that type of structure. Seems like pipenv is the standard for python so I am fine with going with that package manager.

**Comment by afig** [comment]
The structure has been agreed upon, but we will leave this issue open until the folders are created with our first addition of code into the repo.
