### ISSUE TITLE
Add __pycache__ files to .gitignore

### ISSUE THREAD

**Issue by baconbm** [smacademic/project-bdf#39]
**Describe the bug**
When using certain text editors, \__pycache\__ files and folders are being generated

**Expected behavior**
\__pycache\__ folders and files are not included with other changed files when pushing to github.

**Project information**
Bug was noticed in the add-unit-test branch.

**Comment by afig** [comment]
I suggest also adding comments to the `.gitignore` file so that we know what each entry is for. For example, the file might look like:

```
# Cached files generated by some execution environments
__pycache__/

# Manually downloaded credentials
src/authentication.py
```
