### ISSUE TITLE
Create Milestones

### ISSUE THREAD

**Issue by baconbm** [smacademic/project-bdf#4]
This project has a strict deadline since it is part of a course. Because of this, we need to create milestone deadlines so we can stay on track to finish our product by May 9, 2019. Details of the milestone schedule can be worked out as a team.

**Comment by afig** [comment]
As discussed in person, it may not completely appropriate to fully plan out milestones in a project like ours where we are implementing DevOps processes.

Now that we have M1 defined, I think this issue can be closed. What do others think?

**Comment by baconbm** [comment]
I agree, when I created it I was still thinking in the CS305 mindset but since we are using the DevOps mindset it does not make sense to plan out with such granularity so far in advance. This can be closed.
