### ISSUE TITLE
Network issues are not handled when making a connection to Reddit

### ISSUE THREAD

**Issue by afig** [smacademic/project-bdf#45]
**Describe the bug**
If the bot fails to successfully make a connection to Reddit, it throws an exception. This is more of an issue now that the bot is planned to run continuously (see PR #44). If a network failure or Reddit downtime prevents to bot from connecting to Reddit, the bot will stop.

**To Reproduce**
1. Run the bot
2. Turn off the bot's network access (for example, by disconnecting your computer from the internet)
3. Wait for the bot to timeout its network requests (5-30 seconds)

**Expected behavior**
When the bot fails to make a connection to Reddit, it should wait a predefined amount of time and then attempt another connection, rather than quitting completely. This prevents the need to restart the bot after any Reddit downtime or temporary network issues.

**Screenshots/Logs**
Here is an example of an error thrown when there is no network access at all:

```
error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=100&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0DE36AB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

**Project information**
Present since M1, but became more of an issue with the introduction of the bot continuously running (`run-bot-continuously: cc16108a97283e8d26b9b81580bb6608e667fc45)

**Additional context**
The bot should likely wait at least 30 seconds before retrying a connection attempt.

**Comment by baconbm** [comment]
I'm experiencing issues dealing with this exception unless I wrap our main function in a try except block without specifying any exceptions ala 
`try:
            processUsernameMentions(bot)
            time.sleep(5)
        except:
            print("Experiencing network issues, trying again in 30 seconds")
            time.sleep(30)`

When I try to get more granular and list out the specific exceptions that I'm getting it isn't catching them. Do we think this is an acceptable solution? I can keep working at it if not.

**Comment by baconbm** [comment]
Accidentally closed this issue, [this comment is still relevant though](https://github.com/smacademic/project-bdf/issues/45#issuecomment-481421381)
