### ISSUE TITLE
Bot does not detect images if they don't end with .png, .jpg or .tif

### ISSUE THREAD

**Issue by baconbm** [smacademic/project-bdf#63]
**Describe the bug**
The bot does not detect images if they do not end with one of the popular file formats. Some images linked will not end with these file formats and need to be detected.

**To Reproduce**
1. Go to https://www.reddit.com/r/BDFTest/comments/bbszf9/language_transcription_test/
2. Look at the comment by calebeda linking an image
3. See that bot could not detect the link in the post

**Expected behavior**
The bot should be able to detect image links even if they do not end with a popular file format.

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.

**Project information**
Noticed after the M5 release

**Comment by afig** [comment]
Declaring as non-issue since the vast majority of image URLs do not end in anything other than the extension. Trying to avoid this issue will also result in lost of false positives in terms of predicted image URLs.
