### ISSUE TITLE
Our bot's Reddit account does not have API access

### ISSUE THREAD

**Issue by afig** [smacademic/project-bdf#7]
In order to gain API access, our TextifyReddit account needs to have a `script` type app registered to it. The following page has details on how this can be performed: https://github.com/reddit-archive/reddit/wiki/OAuth2-Quick-Start-Example#first-steps

Access to our account's password was discussed in-person.

**Comment by baconbm** [comment]
I think for this issue, we should meet in person and do the initial set up together so we are all on the same page. If only one person handles this issue that could lead to a knowledge silo and I think we all should have a good understanding of how the bot is initially set up.

Thoughts on this?

**Comment by afig** [comment]
I agree with that point @baconbm, it's important that we all see the process of setting this up. An alternative to an in-person meeting is a MS Teams call with screen sharing. Later today let's arrange a time where we can all meet to perform this task.

**Comment by afig** [comment]
Our TextifyReddit bot is now registered as a bot on Reddit. The secret key that will be used for authentication is available upon signing in to the account on Reddit.
