### ISSUE TITLE
There is no template set up for new issue reports

### ISSUE THREAD

**Issue by afig** [smacademic/project-bdf#9]
Setting up a template for new issues will help make issues more consistent and is required as a part of the project's requirements in CS298.

We should probably have separate templates for bug reports and feature requests. GitHub provides some template templates for both bugs and feature requests. I think they work pretty well for our purposes, which some modifications. If necessary, we can always revise our templates later.

I recommend the following changes to the default **bug** template:

- Change "Screenshots" to "Screenshorts/Logs"
- Remove "Desktop" and "Smartphone" sections
- Add a section that captures what version of the product the bug was found in. It may contain:
  - Branch that was checked-out
  - Commit that the bug was noticed in (if you believe that the bug likely existed earlier, please provide the commit that you believe the bug was first introduced in in addition to the commit where it was noticed)

I think the default feature request template looks pretty good as-is. We may want to add a section that asks whether the feature was already part of an extension, or if it was a completely new idea.

Here is the default template for Bugs:

***
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

***
Here is the default template for feature requests:
***

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

***

**Comment by baconbm** [comment]
All your suggestions sound good to me, I can't think of anything more to add. Thank you for the detailed comment @afig
